"""AGENTS.md generation, testing, and revision via the DataRobot LLM gateway."""

import sys
from pathlib import Path

from .config import Config
from .context import gather_context
from .llm import call_llm

MARKER_START = "<!-- AGENTS:GENERATED:START -->"
MARKER_END = "<!-- AGENTS:GENERATED:END -->"

_COPILOT_HEADER = """\
<!-- This file is auto-generated by datarobot-agent-tester — do not edit manually.
     Re-run `task agents-generate` to update.
     Source of truth is the per-directory AGENTS.md files. -->
"""
_COPILOT_PATH = Path(".github") / "copilot-instructions.md"


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------


def _build_generate_prompt(ctx: dict[str, object]) -> str:
    parts = []

    if ctx["is_root"]:
        target_desc = "the ROOT of a monorepo"
        instruction = (
            "Generate a root-level AGENTS.md that:\n"
            "1. Maps the sub-project layout (what each directory is for)\n"
            "2. Lists cross-cutting commands (dev, test, lint, deploy)\n"
            "3. States where shell commands must be run from\n"
            "4. Describes the overall architecture / how services connect\n"
            "Do NOT repeat sub-project-specific details that belong in sub-directory AGENTS.md files."
        )
    else:
        target_desc = f"the `{ctx['target_dir']}/` sub-project"
        instruction = (
            "Generate a sub-project AGENTS.md that:\n"
            "1. States what this sub-project does in 1-2 sentences\n"
            "2. Lists the key directories/files to modify (and what NOT to touch)\n"
            "3. Explains the main conventions and patterns specific to this sub-project\n"
            "4. Lists the exact commands for install/test/lint/dev\n"
            "5. Notes any critical constraints (e.g. generated files, locked methods)\n"
            "Be specific and actionable. Avoid restating obvious things."
        )

    parts.append(
        "You are an expert software engineer writing AGENTS.md files for AI coding assistants.\n"
        "AGENTS.md files guide AI agents working in a codebase — what to modify, what patterns "
        "to follow, and what commands to run.\n\n"
        "IMPORTANT: This file will be loaded into the context window of many different AI coding "
        "tools, including models with small context windows. Write it to be as dense and useful "
        "as possible within a tight budget — every line must earn its place. Prefer bullet points "
        "over prose. Do not pad, repeat, or over-explain.\n\n"
        f"Target: {target_desc}\n\n"
        f"{instruction}\n\n"
        "Output ONLY the markdown content. No preamble, no explanation."
    )

    parts.append(f"\n## Directory structure\n```\n{ctx['tree']}\n```")

    for fname, content in ctx["file_contents"].items():  # type: ignore[union-attr]
        if fname == "AGENTS.md":
            parts.append(
                f"\n## Existing AGENTS.md (for reference / update)\n```markdown\n{content}\n```"
            )
        else:
            parts.append(f"\n## {fname}\n```\n{content}\n```")

    if ctx["copier_answers"]:
        parts.append("\n## Component origins (.datarobot/answers/)")
        for name, content in ctx["copier_answers"].items():  # type: ignore[union-attr]
            parts.append(f"### {name}\n```yaml\n{content}\n```")

    if ctx["sibling_agents_md"]:
        parts.append("\n## Sibling sub-project AGENTS.md files (for context/consistency)")
        for name, content in ctx["sibling_agents_md"].items():  # type: ignore[union-attr]
            parts.append(f"### {name}/AGENTS.md\n```markdown\n{content}\n```")

    return "\n".join(parts)


def _build_test_prompt(agents_md_content: str, ctx: dict[str, object], label: str) -> str:
    target = ctx["target_dir"] if not ctx["is_root"] else "the repository root"
    return f"""\
You are an AI coding assistant assigned to work in {target} of an unfamiliar codebase for the
first time. You have no prior context beyond what is provided below.

You have been handed the following AGENTS.md file ({label}):

<agents_md>
{agents_md_content}
</agents_md>

The actual directory structure of {target} is:
```
{ctx["tree"]}
```

## Your task

Simulate being a first-time agent using this AGENTS.md to complete real work. Go through each
of the following scenarios mentally and report what happens:

1. **Orient yourself** — After reading the AGENTS.md, do you know what this sub-project does,
   what its role is in the larger system, and which files you should look at first?

2. **Make a change** — A user asks you to add a new feature. Do you know which files to modify?
   Which to avoid? Are there patterns or conventions you need to follow?

3. **Run the development loop** — Do you have enough information to install dependencies,
   run tests, and start the dev server? Would any command fail or be ambiguous?

4. **Avoid mistakes** — Are there footguns, generated files, locked methods, or "do not touch"
   areas warned about? Did you feel confident you wouldn't break something?

5. **Identify gaps** — What questions do you still have that you'd have to grep the codebase
   to answer?

## Output format

### What worked well
Specific things the AGENTS.md got right that would save a coding agent time.

### What was unclear or missing
Concrete gaps — things you had to guess at or would need to search for. For each gap, suggest
exactly what text would fix it.

### Commands or instructions that need fixing
Any commands that look wrong, incomplete, or that would fail. Suggest the corrected version.

### Suggested additions
New sections or content that would meaningfully improve agent effectiveness. Write the actual
text where possible.

### Overall verdict
One of: GOOD (minor tweaks only) / NEEDS WORK (several meaningful gaps) / INCOMPLETE
(a new agent would be lost). One sentence explaining why.
"""


def _build_revise_prompt(agents_md_content: str, report: str, ctx: dict[str, object]) -> str:
    target = ctx["target_dir"] if not ctx["is_root"] else "the repository root"
    return f"""\
You are an expert software engineer. You wrote the following AGENTS.md for {target}:

<agents_md>
{agents_md_content}
</agents_md>

A peer reviewer — acting as a first-time agent reading this file — gave the following critique:

<critique>
{report}
</critique>

Your task:
1. For each critique point that is **valid and actionable**, incorporate the fix.
2. For each critique point that is **wrong, already covered, or not relevant**, note it in the
   revision notes (not in the AGENTS.md itself).
3. Output your response in exactly this format — two sections separated by the delimiter:

===AGENTS_MD===
<the complete, updated AGENTS.md — clean markdown only, no reviewer comments>
===REVISION_NOTES===
<a brief list of which critique points you rejected and why>

Maintain the existing style and structure. Do not pad with unnecessary content.
"""


# ---------------------------------------------------------------------------
# Marker helpers
# ---------------------------------------------------------------------------


def strip_markers(text: str) -> str:
    """Remove AGENTS:GENERATED marker comments from content."""
    text = text.replace(MARKER_START + "\n", "").replace(MARKER_START, "")
    text = text.replace("\n" + MARKER_END, "").replace(MARKER_END, "")
    lines = [
        ln
        for ln in text.splitlines()
        if not ln.strip().startswith("<!-- Add custom content below")
    ]
    return "\n".join(lines).strip()


def clean_generated(text: str) -> str:
    """Strip markdown code fences and echoed markers from LLM output."""
    text = text.strip()
    if text.startswith("```"):
        first_newline = text.find("\n")
        text = text[first_newline + 1 :] if first_newline >= 0 else text[3:]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()
    return strip_markers(text).strip()


def apply_generated_content(existing: str, generated: str) -> str:
    """Merge generated content into an existing file using marker blocks."""
    if MARKER_START in existing and MARKER_END in existing:
        before = existing[: existing.index(MARKER_START)]
        after = existing[existing.rindex(MARKER_END) + len(MARKER_END) :]
        return f"{before}{MARKER_START}\n{generated}\n{MARKER_END}{after}"

    custom_note = (
        "\n\n<!-- Add custom content below this line. "
        "It will be preserved when AGENTS.md is regenerated. -->\n"
    )
    result = f"{MARKER_START}\n{generated}\n{MARKER_END}{custom_note}"
    if existing.strip():
        result = result + "\n\n" + existing.strip()
    return result


# ---------------------------------------------------------------------------
# AgentsMd class
# ---------------------------------------------------------------------------


class AgentsMd:
    """Generate, test, and revise AGENTS.md files via the DataRobot LLM gateway.

    Example::

        from dr_agents_tester import Config, AgentsMd
        from pathlib import Path

        cfg = Config()          # reads DATAROBOT_API_TOKEN from env
        cfg.validate()
        agent = AgentsMd(cfg)

        agent.generate(Path("."))          # write/update AGENTS.md
        agent.test(Path("."))              # evaluate and save report
        agent.revise(Path("."))            # apply report feedback
    """

    def __init__(self, config: Config) -> None:
        self.config = config

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        target_dir: Path,
        repo_root: Path | None = None,
        *,
        dry_run: bool = False,
        no_copilot: bool = False,
        model: str | None = None,
    ) -> str:
        """Generate or update AGENTS.md for target_dir.

        Returns the generated markdown string.
        """
        target_dir, repo_root = self._resolve(target_dir, repo_root)
        ctx = gather_context(target_dir, repo_root)
        use_model = model or self.config.model

        print(f"📂 Target:    {ctx['target_dir']}")
        print(f"🏠 Repo root: {repo_root}")
        print(f"🤖 Model:     {use_model}")
        print("⏳ Gathering context...")

        prompt = _build_generate_prompt(ctx)

        print("💬 Calling LLM gateway...")
        generated = call_llm(prompt, use_model, self.config)
        cleaned = clean_generated(generated)

        self._write_agents_md(target_dir, cleaned, dry_run=dry_run)

        if not no_copilot and not dry_run:
            print("📋 Updating .github/copilot-instructions.md...")
            self.write_copilot_instructions(repo_root)

        return cleaned

    def test(
        self,
        target_dir: Path,
        repo_root: Path | None = None,
        *,
        test_model: str | None = None,
    ) -> str:
        """Evaluate the AGENTS.md on disk. Returns and saves the critique report."""
        target_dir, repo_root = self._resolve(target_dir, repo_root)
        ctx = gather_context(target_dir, repo_root)
        use_model = test_model or self.config.test_model

        agents_md_path = target_dir / "AGENTS.md"
        if not agents_md_path.exists():
            print(f"❌ No AGENTS.md found at {agents_md_path}", file=sys.stderr)
            sys.exit(1)

        content = strip_markers(agents_md_path.read_text())

        print(f"🧪 Evaluating AGENTS.md for {ctx['target_dir']}")
        print(f"💬 Evaluating with [{use_model}]...")

        prompt = _build_test_prompt(content, ctx, "as it exists on disk")
        report = call_llm(prompt, use_model, self.config)

        report_path = self._report_path(target_dir)
        report_path.write_text(report)

        print(f"\n{'=' * 60}")
        print(f"AGENTS.md TEST REPORT — {ctx['target_dir']}")
        print(f"{'=' * 60}\n")
        print(report)
        print(f"\n💾 Report saved to {report_path} — run `revise` to apply feedback.")

        return report

    def revise(
        self,
        target_dir: Path,
        repo_root: Path | None = None,
        *,
        dry_run: bool = False,
        no_copilot: bool = False,
        model: str | None = None,
    ) -> str:
        """Apply saved test report feedback to AGENTS.md. Returns updated content."""
        target_dir, repo_root = self._resolve(target_dir, repo_root)
        use_model = model or self.config.model

        report_path = self._report_path(target_dir)
        if not report_path.exists():
            print(
                f"❌ No test report found at {report_path}. Run `test` first.",
                file=sys.stderr,
            )
            sys.exit(1)

        agents_md_path = target_dir / "AGENTS.md"
        if not agents_md_path.exists():
            print(f"❌ No AGENTS.md found at {agents_md_path}", file=sys.stderr)
            sys.exit(1)

        report = report_path.read_text()
        existing = strip_markers(agents_md_path.read_text())
        ctx = gather_context(target_dir, repo_root)

        print(f"✏️  Revising AGENTS.md for {ctx['target_dir']} based on test report...")
        print(f"💬 Revising with [{use_model}]...")

        raw = call_llm(_build_revise_prompt(existing, report, ctx), use_model, self.config)

        if "===AGENTS_MD===" in raw and "===REVISION_NOTES===" in raw:
            agents_part = raw.split("===AGENTS_MD===")[1].split("===REVISION_NOTES===")[0].strip()
            notes_part = raw.split("===REVISION_NOTES===")[1].strip()
        else:
            agents_part = raw.strip()
            notes_part = "(Model did not produce separate revision notes.)"

        if notes_part and not dry_run:
            notes_path = self._revision_notes_path(target_dir)
            notes_path.write_text(notes_part)
            print(f"📝 Revision notes saved to {notes_path}")

        self._write_agents_md(target_dir, agents_part, dry_run=dry_run)

        if not no_copilot and not dry_run:
            print("📋 Updating .github/copilot-instructions.md...")
            self.write_copilot_instructions(repo_root)

        return agents_part

    def write_copilot_instructions(self, repo_root: Path, *, dry_run: bool = False) -> None:
        """Aggregate all AGENTS.md files in the repo into .github/copilot-instructions.md."""
        from .context import EXCLUDE_DIRS

        candidates: list[tuple[str, Path]] = []
        root_agents = repo_root / "AGENTS.md"
        if root_agents.exists():
            candidates.append(("Repository Overview", root_agents))

        for entry in sorted(repo_root.iterdir()):
            if not entry.is_dir() or entry.name in EXCLUDE_DIRS or entry.name.startswith("."):
                continue
            sub_agents = entry / "AGENTS.md"
            if sub_agents.exists():
                candidates.append((f"{entry.name}/", sub_agents))

        if not candidates:
            print("ℹ️  No AGENTS.md files found — skipping copilot-instructions.md")
            return

        sections = [_COPILOT_HEADER.rstrip()]
        for label, path in candidates:
            content = strip_markers(path.read_text()).strip()
            if content:
                sections.append(f"\n---\n\n## {label}\n\n{content}")

        result = "\n".join(sections) + "\n"
        dest = repo_root / _COPILOT_PATH

        if dry_run:
            print(f"\n{'=' * 60}\nDRY RUN — would write to: {dest}\n{'=' * 60}\n")
            print(result)
        else:
            dest.parent.mkdir(exist_ok=True)
            dest.write_text(result)
            print(f"✅ Written: {dest}")

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _resolve(self, target_dir: Path, repo_root: Path | None) -> tuple[Path, Path]:
        from .context import find_repo_root

        target_dir = Path(target_dir).resolve()
        if repo_root is None:
            repo_root = find_repo_root(target_dir)
        else:
            repo_root = Path(repo_root).resolve()
        return target_dir, repo_root

    def _write_agents_md(self, target_dir: Path, generated: str, *, dry_run: bool) -> None:
        agents_md = target_dir / "AGENTS.md"
        existing = agents_md.read_text() if agents_md.exists() else ""
        result = apply_generated_content(existing, clean_generated(generated))

        if dry_run:
            print(f"\n{'=' * 60}\nDRY RUN — would write to: {agents_md}\n{'=' * 60}\n")
            print(result)
        else:
            agents_md.write_text(result)
            print(f"✅ Written: {agents_md}")

    @staticmethod
    def _report_path(target_dir: Path) -> Path:
        return target_dir / ".agents-md-report.md"

    @staticmethod
    def _revision_notes_path(target_dir: Path) -> Path:
        return target_dir / ".agents-md-revision-notes.md"
